### ISSUE TITLE
Output description using images or knit documents

### ISSUE THREAD

**Issue by satviktiwari** [bdslab-upv/covid19-metaclustering#1]
Can the developers release the outputs obtained (in image form or in the form of knit documents)?

**Comment by lexzhou** [comment]
Hi satviktiwari,

Thank for the comment. According to what I can understand from your issue: all the outputs can be obtained by replicating the results executing  **Meta_clustering_tutorial.Rmd**. We have just updated the .Rmd file as well as its HTML version (which can be printed in PDF also) to show some plots that were not available in the previous version. Not sure if this solves your request, feel free to let me know if this does not solve your request.

**Comment by satviktiwari** [comment]
Yeah it's what I had requested for. Thanks for the quick response. I will go through them all. Great work by the way:)
